project_id = "fmcgsxdtyvssvwtxufll"

[functions.ai-generate-clause]
verify_jwt = false

[functions.ai-review-will]
verify_jwt = false

[functions.ai-copilot]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-voice]
verify_jwt = false
