-- Complete the second CSV pack migration by adding remaining missing events
-- Properly cast all types including JSON content

INSERT INTO marketing_events (title, description, event_date, event_type, tags, content_suggestions, created_by, is_active) 
VALUES
  ('Treaty of Ghent Signed', 'The Treaty of Ghent ended the War of 1812 between the United States and Britain', '2024-12-24'::date, 'system', ARRAY['legal-history', 'treaty', 'international-law'], '{"post_ideas": ["Treaty negotiations and legal frameworks", "International dispute resolution", "Post-war legal settlements"], "hashtags": ["#TreatyOfGhent", "#InternationalLaw", "#LegalHistory"]}'::jsonb, NULL, true),
  ('First Continental Congress Convenes', 'The First Continental Congress met in Philadelphia to coordinate colonial resistance to British rule', '2024-09-05'::date, 'system', ARRAY['legal-history', 'constitutional-law', 'colonial-america'], '{"post_ideas": ["Early American governance", "Colonial legal resistance", "Foundation of constitutional principles"], "hashtags": ["#ContinentalCongress", "#ColonialLaw", "#ConstitutionalHistory"]}'::jsonb, NULL, true),
  ('Judiciary Act of 1925', 'Also known as the Judges Bill, this act gave the Supreme Court discretionary jurisdiction through the writ of certiorari', '2025-02-13'::date, 'system', ARRAY['legal-history', 'supreme-court', 'judicial-reform'], '{"post_ideas": ["Supreme Court jurisdiction", "Judicial discretion", "Court system evolution"], "hashtags": ["#JudiciaryAct", "#SupremeCourt", "#JudicialReform"]}'::jsonb, NULL, true),
  ('Sherman Silver Purchase Act', 'Federal legislation requiring the U.S. government to purchase silver, later repealed due to economic concerns', '2024-07-14'::date, 'system', ARRAY['legal-history', 'economic-law', 'federal-legislation'], '{"post_ideas": ["Economic legislation", "Federal monetary policy", "Silver standard debates"], "hashtags": ["#SilverPurchaseAct", "#EconomicLaw", "#MonetaryPolicy"]}'::jsonb, NULL, true),
  ('Federal Trade Commission Act', 'Established the Federal Trade Commission to enforce antitrust laws and protect consumers', '2024-09-26'::date, 'system', ARRAY['legal-history', 'antitrust', 'consumer-protection'], '{"post_ideas": ["Consumer protection laws", "Antitrust enforcement", "Federal regulatory agencies"], "hashtags": ["#FTCAct", "#ConsumerProtection", "#AntitrustLaw"]}'::jsonb, NULL, true),
  ('Civil Rights Act of 1968', 'Landmark legislation that prohibited discrimination in housing, employment, and other areas', '2024-04-11'::date, 'system', ARRAY['legal-history', 'civil-rights', 'housing-law'], '{"post_ideas": ["Fair housing laws", "Civil rights expansion", "Anti-discrimination legislation"], "hashtags": ["#CivilRightsAct1968", "#FairHousing", "#CivilRights"]}'::jsonb, NULL, true),
  ('National Labor Relations Act', 'Also known as the Wagner Act, protected workers right to organize and bargain collectively', '2024-07-05'::date, 'system', ARRAY['legal-history', 'labor-law', 'workers-rights'], '{"post_ideas": ["Workers rights", "Labor unions", "Collective bargaining"], "hashtags": ["#WagnerAct", "#LaborLaw", "#WorkersRights"]}'::jsonb, NULL, true),
  ('Espionage Act of 1917', 'Federal law prohibiting interference with military operations and recruitment during wartime', '2024-06-15'::date, 'system', ARRAY['legal-history', 'national-security', 'wartime-law'], '{"post_ideas": ["Wartime legislation", "National security law", "Free speech debates"], "hashtags": ["#EspionageAct", "#NationalSecurity", "#WartimeLaw"]}'::jsonb, NULL, true),
  ('Social Security Act', 'Established the Social Security system providing old-age benefits and unemployment insurance', '2024-08-14'::date, 'system', ARRAY['legal-history', 'social-security', 'new-deal'], '{"post_ideas": ["Social safety net", "New Deal legislation", "Retirement benefits"], "hashtags": ["#SocialSecurityAct", "#NewDeal", "#SocialSafety"]}'::jsonb, NULL, true),
  ('Immigration and Nationality Act of 1965', 'Abolished national origin quotas and established family reunification as immigration priority', '2024-10-03'::date, 'system', ARRAY['legal-history', 'immigration-law', 'civil-rights'], '{"post_ideas": ["Immigration reform", "Family reunification", "National origin quotas"], "hashtags": ["#ImmigrationAct1965", "#ImmigrationReform", "#CivilRights"]}'::jsonb, NULL, true),
  ('Federal Reserve Act', 'Established the Federal Reserve System as the central banking system of the United States', '2024-12-23'::date, 'system', ARRAY['legal-history', 'banking-law', 'monetary-policy'], '{"post_ideas": ["Central banking", "Monetary policy", "Financial regulation"], "hashtags": ["#FederalReserveAct", "#CentralBanking", "#MonetaryPolicy"]}'::jsonb, NULL, true),
  ('Pure Food and Drug Act', 'First federal law regulating food safety and drug purity in the United States', '2024-06-30'::date, 'system', ARRAY['legal-history', 'food-safety', 'consumer-protection'], '{"post_ideas": ["Food safety regulation", "Consumer protection", "Federal oversight"], "hashtags": ["#PureFoodAct", "#FoodSafety", "#ConsumerProtection"]}'::jsonb, NULL, true),
  ('Glass-Steagall Act', 'Banking legislation that separated commercial and investment banking activities', '2024-06-16'::date, 'system', ARRAY['legal-history', 'banking-law', 'financial-regulation'], '{"post_ideas": ["Banking regulation", "Financial reform", "Investment banking"], "hashtags": ["#GlassSteagall", "#BankingLaw", "#FinancialRegulation"]}'::jsonb, NULL, true),
  ('Civil Rights Act of 1964', 'Landmark legislation prohibiting discrimination based on race, color, religion, sex, or national origin', '2024-07-02'::date, 'system', ARRAY['legal-history', 'civil-rights', 'anti-discrimination'], '{"post_ideas": ["Civil rights milestone", "Anti-discrimination law", "Equal rights"], "hashtags": ["#CivilRightsAct1964", "#CivilRights", "#EqualRights"]}'::jsonb, NULL, true),
  ('Americans with Disabilities Act', 'Comprehensive civil rights law prohibiting discrimination based on disability', '2024-07-26'::date, 'system', ARRAY['legal-history', 'disability-rights', 'civil-rights'], '{"post_ideas": ["Disability rights", "Accessibility requirements", "Civil rights expansion"], "hashtags": ["#ADA", "#DisabilityRights", "#Accessibility"]}'::jsonb, NULL, true),
  ('Voting Rights Act of 1965', 'Landmark legislation that prohibited racial discrimination in voting', '2024-08-06'::date, 'system', ARRAY['legal-history', 'voting-rights', 'civil-rights'], '{"post_ideas": ["Voting rights protection", "Electoral access", "Civil rights enforcement"], "hashtags": ["#VotingRightsAct", "#VotingRights", "#CivilRights"]}'::jsonb, NULL, true),
  ('Fair Credit Reporting Act', 'Federal law regulating the collection and use of consumer credit information', '2024-10-26'::date, 'system', ARRAY['legal-history', 'consumer-protection', 'privacy'], '{"post_ideas": ["Credit reporting", "Consumer privacy", "Financial protection"], "hashtags": ["#FCRA", "#ConsumerProtection", "#CreditReporting"]}'::jsonb, NULL, true),
  ('Employee Retirement Income Security Act', 'Federal law establishing minimum standards for pension and health plans', '2024-09-02'::date, 'system', ARRAY['legal-history', 'employee-benefits', 'pension-law'], '{"post_ideas": ["Employee benefits", "Pension protection", "Retirement security"], "hashtags": ["#ERISA", "#EmployeeBenefits", "#PensionLaw"]}'::jsonb, NULL, true),
  ('Clean Air Act', 'Federal law regulating air emissions from stationary and mobile sources', '2024-12-17'::date, 'system', ARRAY['legal-history', 'environmental-law', 'public-health'], '{"post_ideas": ["Environmental protection", "Air quality standards", "Public health law"], "hashtags": ["#CleanAirAct", "#EnvironmentalLaw", "#PublicHealth"]}'::jsonb, NULL, true),
  ('Occupational Safety and Health Act', 'Federal law requiring employers to provide safe and healthy working conditions', '2024-12-29'::date, 'system', ARRAY['legal-history', 'workplace-safety', 'labor-law'], '{"post_ideas": ["Workplace safety", "Employee protection", "Occupational health"], "hashtags": ["#OSHA", "#WorkplaceSafety", "#LaborLaw"]}'::jsonb, NULL, true)
ON CONFLICT DO NOTHING;