// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmcgsxdtyvssvwtxufll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtY2dzeGR0eXZzc3Z3dHh1ZmxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NTk2MjcsImV4cCI6MjA3MDMzNTYyN30.VC_lIcDwR_0EJrIROf7E8809pxkUPco8mPKd_s30UVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});